UKP-SQuARE/square-core

docs/pages/components/models.md
=> Square docs

square-model-inference-api/README.md
=> changed localhost to square public website and bart deployment example

config.yaml, skills/generative-qa/skill.py, skills/requirements.txt
Co-authored-by: Tim Baumgärtner <timbmg@users.noreply.github.com>
=> narrativeqa added!!

square-frontend/public/index.html, square-frontend/src/views/Terms.vue
Add google analytics and a banner to the home page
=> Frontend UI

datastore-api/app/core/es/connector.py, datastore-api/app/core/kgs/class_converter.py, datastore-api/app/core/kgs/connector.py, datastore-api/app/routers/api.py, datastore-api/app/routers/datastores.py, datastore-api/app/routers/dependencies.py, datastore-api/app/routers/documents.py, datastore-api/app/routers/kgs.py
Hi Tim,
There might follow an update on the GET-Subgraph Request, but for now this is the KG-API.
Greetings Sewin
=> Datastores with KGs

datastore-api/app/core/kgs/connector.py, datastore-api/app/routers/kgs.py
Small addition for making the qagnn pipeline work
=> Added GET-Request for retrieving In- and Out-nodes as a list of nids

square-frontend/src/components/modals/ExplainOutput.vue
- new api format
- buttons are more responsive
- highlighting all words
- tooltip shows the real grad value
🚀
=> Responsive saliency map

square-frontend/src/api/index.js, square-frontend/src/components/modals/ExplainOutput.vue
Saliency maps for ODQA are working!
=> UI return doc odqa

square-frontend/src/api/index.js, square-frontend/src/components/modals/ExplainOutput.vue, square-frontend/src/store/index.js
This PR creates an alert message when the explainability api takes more than 8 seconds. I'll show some screenshots tmr to change the aesthetics if needed
=> Waiting msg

skill-manager/requirements.txt, skill-manager/skill_manager/core/session_cache.py, skill-manager/skill_manager/models.py, skill-manager/skill_manager/routers/skill.py, skill-manager/tests/test_api.py
Fixes init of created_at of a Skill that caused new cache keys for skill when created_at was not initialized
=> Fix Caching for QA-GNN

square-model-inference-api/inference_server/tasks/inference/graph_transformers.py
Add softmax function to normalize the LM score.
Change 'width' to 'weight' of node info.
=> Model api v2

square-model-inference-api/inference_server/tasks/inference/graph_transformers.py
change the name of attn from `width` to `weight`
=> change the name of attn from width to weight

square-frontend/src/components/Results.vue, square-frontend/src/components/modals/AttackOutput.vue
=> Disabling attack methods to non span-extraction skills

square-frontend/src/components/modals/ExplainDetail.vue
This is a temporary fix. The current UI for behave. tests is broken. I reverted to v1 (last thing Max committed). When we deploy again the open-domain tests, I will fix the issues (I don't have the tests right now)
=> back to v1 behavioral tests. Working on span extraction

square-model-inference-api/inference_server/tasks/inference/graph_transformers.py
fix the bug in reporting the edge information.
Reviewer:Rachneet
- frontend: @HaritzPuerto
- models: @Rachneet
- docs: @Rachneet
=> fix:fix edge error in qagnn

square-frontend/src/components/Query.vue, square-frontend/src/components/modals/AttackOutput.vue, square-frontend/src/components/modals/ExplainOutput.vue, square-frontend/src/store/index.js
fixing the bug that makes explainability and attack break
=> Fix Bug Choices and Explain and Attack API Calls

docker-compose.ytt.yaml, skill-manager/.gitignore, skill-manager/.local.env, skill-manager/.pre-commit-config.yaml, skill-manager/Dockerfile, skill-manager/Makefile, skill-manager/README.md, skill-manager/api.http, skill-manager/docker-compose.yaml, skill-manager/requirements.dev.txt, skill-manager/requirements.txt, skill-manager/skill_manager/__init__.py, skill-manager/skill_manager/auth_utils.py, skill-manager/skill_manager/core/redis_client.py, skill-manager/skill_manager/core/session_cache.py, skill-manager/skill_manager/keycloak_api.py, skill-manager/skill_manager/main.py, skill-manager/skill_manager/models.py, skill-manager/skill_manager/mongo/mongo_model.py, skill-manager/skill_manager/routers/skill.py, skill-manager/skill_manager/settings/__init__.py, skill-manager/tests/conftest.py, skill-manager/tests/test_api.py, skill-manager/tests/test_keycloak_api.py, skill-manager/tests/testcontainer_keycloak.py
Support simple local deployment of the skill-manager.
=> Skill Manager Local Deployment

datastore-api/Makefile, datastore-api/requirements.dev.txt, datastore-api/requirements.txt, datastore-api/tests/conftest.py, datastore-api/tests/test_datastores.py, datastore-api/tests/test_documents.py, datastore-api/tests/test_indices.py, datastore-api/tests/test_query.py, datastore-api/tests/utils.py
=> [DS-1] Use real containers for es and mongo

.github/workflows/build.yml, .github/workflows/deploy.yml
Trigger a webhook for deploying to test or prod. The deployment can be triggered manually on any branch or will be run automatically when creating a release.
=> Deploy Automation

frontend/package-lock.json, frontend/src/components/modals/GraphViz.vue
Fixes the viz of choices in the graph viz
=> Fix choices viz4gagnn

frontend/src/components/CompareSkills.vue
Fixes small bugs on the new UI
=> fix responsiveness skill selector

skills/.gitignore, skills/.pre-commit-config.yaml, skills/Makefile, skills/README.md, skills/boolq/skill.py, skills/commonsense-qa/skill.py, skills/extractive-qa/skill.py, skills/generative-qa/skill.py, skills/information-retrieval/skill.py, skills/local/skill.py, skills/main.py, skills/multiple-choice-qa/skill.py, skills/open-extractive-qa/skill.py, skills/open-generative-qa/skill.py, skills/qa-gnn/skill.py, skills/requirements.dev.txt, skills/requirements.txt
Adds local setup instructions for skill development.
=> Local Setup for Skills

frontend/package.json, frontend/src/api/index.js, frontend/src/views/Skill.vue
=> Skill args UI

.github/workflows/build-and-deploy.yml, config.yaml, docker-compose.ytt.min.yaml, docker-compose.ytt.yaml, frontend/.env.development, frontend/.env.production, frontend/.env.test, frontend/Dockerfile, frontend/package.json, frontend/public/index.html, frontend/src/views/Terms.vue, square-model-inference-api/inference_server/Dockerfile, square-model-inference-api/inference_server/requirements1.txt, square-model-inference-api/inference_server/tasks/inference/transformer.py
When building for production the frontend will use `frontend/env.production`, for test `frontend/env.test`.
=> Frontend and Model-Inference fixes for test env

skill-manager/docker-compose.yaml
deploys a skill along with the skill-manager
=> extractive qa skill deployment with skill manager

model-inference/dockerfiles/base_model/requirements.txt, model-inference/model_inference/tasks/inference/transformer.py, model-inference/model_inference/tasks/models/prediction.py
=> Added bertviz backend

frontend/package-lock.json, frontend/package.json, frontend/src/components/CompareSkills.vue, frontend/src/views/Skill.vue, skill-manager/skill_manager/models.py, skills/extractive-qa/skill.py, skills/multiple-choice-qa/skill.py
Model-Inference API still needs support for this @Rachneet
=> UI to combine adapters is ready!

datastore-api/app/core/startup.py, datastore-api/app/routers/query.py, skills/open-extractive-qa/skill.py
- fix `wait_for_up` on ES
- add logging to /search
- add option to set number of documents that shall be retrieved
=> Fix for datastores Bing Search

model-inference/model_inference/tasks/inference/transformer.py
=> hotfix bertviz backend

model-inference/model_inference/tasks/inference/transformer.py, model-inference/model_inference/tasks/models/prediction.py
=> Bertviz backend hotfix | html object

datastore-api/app/routers/kgs.py
Fix https://github.com/UKP-SQuARE/square-core/issues/391
=> DS: Correct the put node method

.github/workflows/build-and-deploy.yml, config.yaml, docker-compose.models.yml, model-inference/model_configurations/.env.metaqa, model-inference/model_inference/tasks/inference/metaqa.py, skill-manager/requirements.txt, skills/extractive-metaqa/skill.py, skills/metaqa/skill.py, skills/requirements.txt
MetaQA is working. There are some details left, but we can sort them in v3 branch
=> Model api v3 metaqa

skills/extractive-metaqa/skill.py, skills/metaqa/skill.py, skills/multiple-choice-metaqa/skill.py
=> added task_kwargs.topk

model-inference/model_inference/tasks/inference/transformer.py, model-inference/model_inference/tasks/tasks.py
1. fixes bertviz and attack methods
- [y] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [y] Did you make sure to update the documentation with your changes?
- [y] Did you write any new necessary tests?
=> Model api v3

model-inference/model_inference/tasks/inference/metaqa.py, model-inference/tests/pre_test_setup_for_docker_caching.py, model-manager/model_manager/app/routers/management.py, model-manager/tests/test_onnx_deploy.py
This PR returns probabilities for MetaQA.
Other minor changes:
Code reformatting
=> Meta QA probabilities

frontend/src/views/Skill.vue
=> fix UI editing metaqa

frontend/src/components/Query.vue
=> generative models don't need context anymore

frontend/src/components/Results.vue, frontend/src/components/results/Abstractive.vue
=> added abstrative results view

frontend/src/components/CompareSkills.vue, frontend/src/components/Query.vue, frontend/src/store/index.js, frontend/src/views/QA.vue
Now when we move from QA to another page and then go back to QA, QA page is reset
=> reset internal variables of QA page on leave

model-manager/model_manager/app/models/onnx_export.py
Resolves an issue during the ONNX export for models with QA heads by using the correct model classes instead of AutoModel.
@HaritzPuerto
@Rachneet
=> Fix: Use correct model classes during ONNX export

model-inference/model_inference/app/api/routes/prediction.py, model-inference/model_inference/tasks/inference/metaqa.py, model-inference/model_inference/tasks/tasks.py, model-manager/model_manager/app/db/database.py, model-manager/model_manager/app/models/onnx_export.py, model-manager/model_manager/app/routers/management.py, model-manager/model_manager/docker_access.py
Bug fixes:
1. Correct health endpoint for models
2. ONNX export for QA models
-->
=> Bug fixes for models health and ONNX export

docker-compose.ytt.yaml, model-manager/model_manager/app/routers/management.py, model-manager/model_manager/docker_access.py
=> fix: models heath w/o using db

frontend/src/main.js
Keycloack now is working on local deployment of UI and on test vm. I tested logging, creating a new eval, access to edit, and personal info in the keycloak menu. All works :)
I think we can merge, unless @timbmg wants to test something else.
=> keycloack working in local deployment

model-manager/Dockerfile, model-manager/config.ini, model-manager/model_manager/app/core/config.py, model-manager/model_manager/app/db/database.py, model-manager/model_manager/main.py
- Remove model manager auth
- Better config management
=> Model manager auth

frontend/src/components/Results.vue, frontend/src/components/modals/AttackOutput.vue, frontend/src/components/modals/ExplainOutput.vue, frontend/src/views/QA.vue
remove model auth
It just make sure that the selectedSkills is passed properly to the AttackOutput view to be able to use the attack methods. 
@HaritzPuerto
=> Fixed the problem of attack method not working with the new UI

frontend/checklist/63a61a162e30fd4c06f7a0b6.json, frontend/checklist/63a61c802e30fd4c06f7a0b7.json, frontend/checklist/63a61cc32e30fd4c06f7a0b8.json, frontend/checklist/63a61ce70bf4c04a19c59dc8.json, frontend/checklist/63a61d300bf4c04a19c59dc9.json, frontend/checklist/63a61d7d2e30fd4c06f7a0b9.json, frontend/checklist/63a61db22e30fd4c06f7a0ba.json, frontend/checklist/63a6246c2e30fd4c06f7a0be.json
This PR just adds new behavioral tests for span-bert models.
=> add new behavioral tests for span-bert models

frontend/src/api/index.js, frontend/src/components/Query.vue
This PR solves the issue of time out after 30s when deploying large models. It still have one issue of spinners not showing up when waiting for the weights of the models to be downloaded.
=> Dynamic_model_deployment

datastore-api/app/routers/documents.py, datastore-api/app/routers/kgs.py, datastore-api/requirements.txt
Fixate the Pydantic version to prevent it from downloading V2 which changes lots of the library's interface. 
@HaritzPuerto
=> fix: datastores update requirements

frontend/src/views/Chatbot.vue
Fixed implementation of the rating interface
=> Dasp profile user feedback with fixed calculations

frontend/src/views/Skill.vue, local_deploy/requirements.txt, model-manager/model_manager/app/models/management.py, model-manager/model_manager/app/routers/management.py, model-manager/model_manager/tasks/tasks.py, skill-manager/.local.env, skill-manager/Dockerfile, skill-manager/Makefile, skill-manager/requirements.txt, skills/requirements.txt
This PR fixes the issue of creating new skills. The main problem was some inconsistencies in interfaces in the (1) frontend (2) models (3) skill-model-client.
=> Fix skill creation
